spring: 
    profiles: 
        active:
           - dev
---
server: 
    port: 8201
spring:
    profiles: dev
    application:
        name: springcloud-config-client-dev
eureka:
    client: 
        service-url: 
            defaultZone: http://localhost:7001/eureka/
---
server: 
    port: 8202
spring:
    profiles: test
    application:
        name: springcloud-config-client-test
eureka:
    client: 
        service-url: 
            defaultZone: http://localhost:7001/eureka/